DEFINE TABLE DCM_LEARNING.{{schema_name}}.ORDERS_RAW (
    ORDER_ID     NUMBER,
    CUSTOMER_ID  NUMBER,
    ORDER_DATE   DATE,
    AMOUNT       NUMBER(10,2)
);

-- DEV role
DEFINE ROLE dbt_dev_role
    COMMENT = 'Least-privilege role for dbt DEV runs';
GRANT CREATE TABLE ON SCHEMA DCM_LEARNING.TEST TO ROLE dbt_dev_role;
GRANT USAGE ON DATABASE DCM_LEARNING TO ROLE dbt_dev_role;
GRANT USAGE ON SCHEMA DCM_LEARNING.TEST TO ROLE dbt_dev_role;
GRANT SELECT, INSERT ON TABLE DCM_LEARNING.TEST.ORDERS_RAW TO ROLE dbt_dev_role;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE dbt_dev_role;
GRANT CREATE VIEW ON SCHEMA DCM_LEARNING.TEST TO ROLE dbt_dev_role;

-- PROD role
DEFINE ROLE dbt_prod_role
    COMMENT = 'Least-privilege role for dbt PROD runs';

GRANT USAGE ON DATABASE DCM_LEARNING TO ROLE dbt_prod_role;
GRANT USAGE ON SCHEMA DCM_LEARNING.PROD TO ROLE dbt_prod_role;
GRANT SELECT, INSERT ON TABLE DCM_LEARNING.PROD.ORDERS_RAW TO ROLE dbt_prod_role;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE dbt_prod_role;
GRANT CREATE VIEW ON SCHEMA DCM_LEARNING.PROD TO ROLE dbt_prod_role;
GRANT CREATE TABLE ON SCHEMA DCM_LEARNING.PROD TO ROLE dbt_prod_role;


GRANT ROLE dbt_dev_role TO USER RAGHAVVENKATACHARI;
GRANT ROLE dbt_prod_role TO USER RAGHAVVENKATACHARI;
